services:

    cheatsheet-mongodb:
        image: mongo:4.4.18
        container_name: cheatsheet-mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS:-mysecretpass}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-cheatsheetdb}
        ports:
            - "${MONGO_PORT:-14002}:27017"
        volumes:
            - ./mount/mongo_data:/data/db

    cheatsheet-api:
        image: ghcr.io/eliedersousa/cheatsheetcreator-api:latest
        container_name: cheatsheet-api
        restart: unless-stopped
        ports:
            - "${API_PORT:-14001}:8080"
        depends_on:
            - cheatsheet-mongodb
        environment:
            SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASS:-mysecretpass}@cheatsheet-mongodb:27017/${MONGO_DATABASE:-cheatsheetdb}?authSource=admin
            API_KEY: ${VITE_API_KEY}
            CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
            RATE_LIMIT: ${RATE_LIMIT}

    cheatsheet-frontend:
        image: ghcr.io/eliedersousa/cheatsheetcreator-frontend:latest
        container_name: cheatsheet-frontend
        restart: unless-stopped
        depends_on: cheatsheet-api
        ports:
            - "${FRONTEND_PORT:-14000}:80"
        environment:
            - VITE_API_KEY= ${VITE_API_KEY}
            - VITE_API_SERVER= ${VITE_API_SERVER:-cheatsheet-api:14001}
